version: '3.8'

services:
  app:
    image: jhipster-app:latest
    container_name: jhipster-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jhipster
      SPRING_DATASOURCE_USERNAME: jhipster
      SPRING_DATASOURCE_PASSWORD: jhipster
      JHIPSTER_SLEEP: 10

  db:
    image: postgres:15
    container_name: jhipster-db
    environment:
      POSTGRES_USER: jhipster
      POSTGRES_PASSWORD: jhipster
      POSTGRES_DB: jhipster
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
